package github

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/url"
	"os/exec"
	"strconv"
	"strings"
)

// ErrNotActionsRun is returned by CheckLogs when a check's details URL is not
// a GitHub Actions run (e.g. CircleCI, Vercel). Callers can errors.Is on it to
// skip such checks quietly rather than logging a failure.
var ErrNotActionsRun = errors.New("not a GitHub Actions run")

// Client is a `gh`-CLI wrapper. Stateless — safe to use concurrently.
type Client struct{}

// New returns a ready-to-use Client.
func New() *Client { return &Client{} }

// NoctraPRBodyMarker is a hidden marker embedded in every PR body Noctra
// generates (ticket and sweep alike), used to identify its own PRs.
const NoctraPRBodyMarker = "<!-- noctra-authored -->"

// legacyNoctraPRBodyMarker matches PRs created before the hidden marker
// existed; both old footers contain it.
const legacyNoctraPRBodyMarker = "by [Noctra]"

// IsNoctraAuthoredBody reports whether a PR body was generated by Noctra.
func IsNoctraAuthoredBody(body string) bool {
	return strings.Contains(body, NoctraPRBodyMarker) ||
		strings.Contains(body, legacyNoctraPRBodyMarker)
}

// ListNoctraPRs returns every open PR that Noctra created across the
// given repositories (authored by the current `gh` user, with a `noctra/`
// branch and Noctra's generated PR body marker).
//
// repoURLs are the git URLs of the repos Noctra has cloned (plus the
// REPO_PATH fallback). Each is reduced to `owner/name` before being passed to
// `gh`. Per-repo errors are logged (not returned) so a single unreachable repo
// doesn't kill the whole sweep.
func (c *Client) ListNoctraPRs(ctx context.Context, repoURLs []string) ([]PR, error) {
	var out []PR
	for _, raw := range repoURLs {
		ownerRepo, err := ExtractOwnerRepo(raw)
		if err != nil {
			slog.Warn("github: skipping repo (cannot extract owner/name)", "url", raw, "err", err)
			continue
		}

		var stderr strings.Builder
		cmd := exec.CommandContext(ctx, "gh", "pr", "list",
			"--repo", ownerRepo,
			"--author", "@me",
			"--state", "open",
			"--json", "url,number,title,headRefName,body",
		)
		cmd.Stderr = &stderr
		stdout, err := cmd.Output()
		if err != nil {
			slog.Warn("github: gh pr list failed", "repo", ownerRepo, "err", err, "stderr", strings.TrimSpace(stderr.String()))
			continue
		}

		var prs []PR
		if err := json.Unmarshal(stdout, &prs); err != nil {
			slog.Warn("github: decode pr list output", "repo", ownerRepo, "err", err)
			continue
		}

		for _, pr := range prs {
			if !strings.HasPrefix(pr.HeadRefName, "noctra/") {
				continue
			}
			if IsNoctraAuthoredBody(pr.Body) {
				// Remember the remote this PR was found through so the iterate
				// path can re-resolve over the same transport (e.g. SSH).
				pr.RepoURL = raw
				out = append(out, pr)
			} else {
				slog.Warn("github: skipping noctra-prefixed PR without Noctra body marker",
					"repo", ownerRepo, "pr", pr.Number, "branch", pr.HeadRefName)
			}
		}
	}
	return out, nil
}

// GetPR fetches the full view of a PR — comments, reviews, state — used by
// the watcher to diff against the state cursor.
func (c *Client) GetPR(ctx context.Context, prURL string) (*Details, error) {
	var stderr strings.Builder
	cmd := exec.CommandContext(ctx, "gh", "pr", "view", prURL,
		"--json", "url,number,state,headRefOid,comments,reviews,statusCheckRollup",
	)
	cmd.Stderr = &stderr
	stdout, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("gh pr view %s: %w (%s)", prURL, err, strings.TrimSpace(stderr.String()))
	}
	var d Details
	if err := json.Unmarshal(stdout, &d); err != nil {
		return nil, fmt.Errorf("decode gh pr view %s: %w", prURL, err)
	}

	// Inline review-thread comments aren't returned by `gh pr view`; pull
	// them from the REST API. Non-fatal: on failure we degrade to
	// conversation comments + review summaries rather than skipping the PR.
	if rc, err := c.listReviewComments(ctx, prURL); err != nil {
		slog.Warn("github: fetch inline review comments failed", "url", prURL, "err", err)
	} else {
		d.ReviewComments = rc
	}
	return &d, nil
}

// listReviewComments fetches the inline review-thread comments for a PR via
// the REST API (paginated — bots can leave many on one review).
func (c *Client) listReviewComments(ctx context.Context, prURL string) ([]ReviewComment, error) {
	apiPath, err := reviewCommentsAPIPath(prURL)
	if err != nil {
		return nil, err
	}
	var stderr strings.Builder
	cmd := exec.CommandContext(ctx, "gh", "api", "--paginate", apiPath)
	cmd.Stderr = &stderr
	stdout, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("gh api %s: %w (%s)", apiPath, err, strings.TrimSpace(stderr.String()))
	}
	comments, err := decodeReviewComments(stdout)
	if err != nil {
		return nil, fmt.Errorf("decode review comments %s: %w", apiPath, err)
	}
	return comments, nil
}

// decodeReviewComments parses the output of `gh api --paginate`. Depending on
// the gh version this is either a single merged JSON array or several arrays
// concatenated (one per page); a streaming decoder handles both.
func decodeReviewComments(stdout []byte) ([]ReviewComment, error) {
	dec := json.NewDecoder(bytes.NewReader(stdout))
	var comments []ReviewComment
	for dec.More() {
		var page []ReviewComment
		if err := dec.Decode(&page); err != nil {
			return nil, err
		}
		comments = append(comments, page...)
	}
	return comments, nil
}

// maxCheckLogBytes caps how much of a failed check's log we feed back to
// Claude — the tail almost always holds the actual error, and an unbounded
// log would blow up the prompt.
const maxCheckLogBytes = 6000

// CheckLogs returns the failed-step logs for a check, truncated to the tail.
// Only GitHub Actions runs are supported; other check kinds (whose details
// URL isn't an Actions run) return an error the caller treats as best-effort.
func (c *Client) CheckLogs(ctx context.Context, ch Check) (string, error) {
	owner, repo, runID, ok := parseActionsRunURL(ch.URL())
	if !ok {
		return "", fmt.Errorf("%q: %w", ch.URL(), ErrNotActionsRun)
	}
	var stderr strings.Builder
	cmd := exec.CommandContext(ctx, "gh", "run", "view", runID,
		"--repo", owner+"/"+repo, "--log-failed")
	cmd.Stderr = &stderr
	stdout, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("gh run view %s: %w (%s)", runID, err, strings.TrimSpace(stderr.String()))
	}
	return tailString(string(stdout), maxCheckLogBytes), nil
}

// tailString returns the last max bytes of s, prefixed with a truncation
// marker when it had to cut.
func tailString(s string, max int) string {
	if len(s) <= max {
		return s
	}
	start := len(s) - max
	// Don't slice mid-rune: skip past any UTF-8 continuation bytes (top two
	// bits == 10) so the result stays valid UTF-8.
	for start < len(s) && s[start]&0xC0 == 0x80 {
		start++
	}
	return "...(truncated)\n" + s[start:]
}

// parseActionsRunURL extracts owner, repo and run ID from a GitHub Actions
// check details URL like
// https://github.com/owner/repo/actions/runs/123/job/456.
func parseActionsRunURL(raw string) (owner, repo, runID string, ok bool) {
	u, err := url.Parse(raw)
	if err != nil {
		return "", "", "", false
	}
	parts := strings.Split(strings.Trim(u.Path, "/"), "/")
	// owner / repo / actions / runs / <id> [...]
	if len(parts) < 5 || parts[2] != "actions" || parts[3] != "runs" {
		return "", "", "", false
	}
	if parts[0] == "" || parts[1] == "" || parts[4] == "" {
		return "", "", "", false
	}
	return parts[0], parts[1], parts[4], true
}

// reviewCommentsAPIPath turns a PR URL into the REST path for its inline
// review comments: https://github.com/owner/name/pull/12 →
// repos/owner/name/pulls/12/comments.
func reviewCommentsAPIPath(prURL string) (string, error) {
	u, err := url.Parse(prURL)
	if err != nil {
		return "", fmt.Errorf("parse PR URL %q: %w", prURL, err)
	}
	parts := strings.Split(strings.Trim(u.Path, "/"), "/")
	if len(parts) < 4 || parts[2] != "pull" || parts[0] == "" || parts[1] == "" || parts[3] == "" {
		return "", fmt.Errorf("unexpected PR URL shape: %q", prURL)
	}
	return fmt.Sprintf("repos/%s/%s/pulls/%s/comments", parts[0], parts[1], parts[3]), nil
}

// ExtractOwnerRepo reduces a git remote URL (SSH or HTTPS) to its `owner/name`
// form, which is what `gh --repo` wants. An already-reduced "owner/name" is
// returned as-is.
//
//	git@github.com:me/auth.git   → me/auth
//	https://github.com/me/auth   → me/auth
//	me/auth                      → me/auth
func ExtractOwnerRepo(raw string) (string, error) {
	s := strings.TrimSuffix(strings.TrimSpace(raw), ".git")

	if strings.HasPrefix(s, "git@") {
		idx := strings.Index(s, ":")
		if idx < 0 {
			return "", fmt.Errorf("ssh URL missing ':' in %q", raw)
		}
		rest := s[idx+1:]
		if !looksLikeOwnerRepo(rest) {
			return "", fmt.Errorf("unexpected ssh URL shape: %q", raw)
		}
		return rest, nil
	}

	if strings.HasPrefix(s, "https://") || strings.HasPrefix(s, "http://") {
		u, err := url.Parse(s)
		if err != nil {
			return "", fmt.Errorf("parse URL %q: %w", raw, err)
		}
		rest := strings.Trim(u.Path, "/")
		if !looksLikeOwnerRepo(rest) {
			return "", fmt.Errorf("URL path %q is not owner/name", u.Path)
		}
		return rest, nil
	}

	if looksLikeOwnerRepo(s) {
		return s, nil
	}
	return "", fmt.Errorf("cannot extract owner/name from %q", raw)
}

func looksLikeOwnerRepo(s string) bool {
	return strings.Count(s, "/") == 1 && !strings.HasPrefix(s, "/") && !strings.HasSuffix(s, "/")
}

// reviewThread is an unresolved review thread on a PR, fetched via GraphQL.
type reviewThread struct {
	ID                     string // GraphQL node ID (used to resolve the thread)
	FirstCommentDatabaseID int64  // REST API ID of the first comment (used to reply)
}

// ReplyAndResolveThreads replies to and resolves all unresolved review threads
// on a PR with a short note referencing the new commit SHA. Best-effort:
// individual failures are logged, never returned. Mirrors the existing
// "non-fatal on failure" posture for inline-comment fetches.
func (c *Client) ReplyAndResolveThreads(ctx context.Context, prURL, sha string) {
	owner, repo, number, err := parsePRURL(prURL)
	if err != nil {
		slog.Warn("github: cannot parse PR URL for thread resolution", "url", prURL, "err", err)
		return
	}

	threads, err := c.fetchUnresolvedThreads(ctx, owner, repo, number)
	if err != nil {
		slog.Warn("github: fetch review threads failed", "url", prURL, "err", err)
		return
	}

	if len(threads) == 0 {
		return
	}

	replyBody := fmt.Sprintf("Addressed in %s.", sha)

	resolved := 0
	for _, t := range threads {
		if t.FirstCommentDatabaseID > 0 {
			if err := c.replyToThread(ctx, owner, repo, number, t.FirstCommentDatabaseID, replyBody); err != nil {
				slog.Warn("github: reply to review thread failed", "thread", t.ID, "err", err)
			}
		}
		if err := c.resolveThread(ctx, t.ID); err != nil {
			slog.Warn("github: resolve review thread failed", "thread", t.ID, "err", err)
		} else {
			resolved++
		}
	}

	slog.Info("github: review threads addressed", "url", prURL, "total", len(threads), "resolved", resolved)
}

// fetchUnresolvedThreads queries the GitHub GraphQL API for all unresolved
// review threads on a PR. Returns only threads that are not yet resolved.
func (c *Client) fetchUnresolvedThreads(ctx context.Context, owner, repo string, number int) ([]reviewThread, error) {
	query := `query($owner: String!, $repo: String!, $number: Int!) {
  repository(owner: $owner, name: $repo) {
    pullRequest(number: $number) {
      reviewThreads(first: 100) {
        nodes {
          id
          isResolved
          comments(first: 1) {
            nodes {
              databaseId
            }
          }
        }
      }
    }
  }
}`

	var stderr strings.Builder
	cmd := exec.CommandContext(ctx, "gh", "api", "graphql",
		"-f", "query="+query,
		"-f", "owner="+owner,
		"-f", "repo="+repo,
		"-F", fmt.Sprintf("number=%d", number),
	)
	cmd.Stderr = &stderr
	stdout, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("gh api graphql: %w (%s)", err, strings.TrimSpace(stderr.String()))
	}

	return decodeReviewThreads(stdout)
}

// decodeReviewThreads parses the GraphQL response for review threads and
// returns only the unresolved ones.
func decodeReviewThreads(data []byte) ([]reviewThread, error) {
	var resp struct {
		Data struct {
			Repository struct {
				PullRequest struct {
					ReviewThreads struct {
						Nodes []struct {
							ID         string `json:"id"`
							IsResolved bool   `json:"isResolved"`
							Comments   struct {
								Nodes []struct {
									DatabaseID int64 `json:"databaseId"`
								} `json:"nodes"`
							} `json:"comments"`
						} `json:"nodes"`
					} `json:"reviewThreads"`
				} `json:"pullRequest"`
			} `json:"repository"`
		} `json:"data"`
	}
	if err := json.Unmarshal(data, &resp); err != nil {
		return nil, fmt.Errorf("decode review threads: %w", err)
	}

	var threads []reviewThread
	for _, n := range resp.Data.Repository.PullRequest.ReviewThreads.Nodes {
		if n.IsResolved {
			continue
		}
		var commentID int64
		if len(n.Comments.Nodes) > 0 {
			commentID = n.Comments.Nodes[0].DatabaseID
		}
		threads = append(threads, reviewThread{
			ID:                     n.ID,
			FirstCommentDatabaseID: commentID,
		})
	}
	return threads, nil
}

// replyToThread posts a reply on a review comment thread via the REST API.
func (c *Client) replyToThread(ctx context.Context, owner, repo string, prNumber int, commentID int64, body string) error {
	apiPath := fmt.Sprintf("repos/%s/%s/pulls/%d/comments/%d/replies", owner, repo, prNumber, commentID)
	var stderr strings.Builder
	cmd := exec.CommandContext(ctx, "gh", "api", "--method", "POST", apiPath,
		"-f", "body="+body,
	)
	cmd.Stderr = &stderr
	if _, err := cmd.Output(); err != nil {
		return fmt.Errorf("gh api POST %s: %w (%s)", apiPath, err, strings.TrimSpace(stderr.String()))
	}
	return nil
}

// resolveThread resolves a review thread via the GitHub GraphQL API.
func (c *Client) resolveThread(ctx context.Context, threadID string) error {
	mutation := `mutation($threadId: ID!) {
  resolveReviewThread(input: {threadId: $threadId}) {
    thread { isResolved }
  }
}`

	var stderr strings.Builder
	cmd := exec.CommandContext(ctx, "gh", "api", "graphql",
		"-f", "query="+mutation,
		"-f", "threadId="+threadID,
	)
	cmd.Stderr = &stderr
	if _, err := cmd.Output(); err != nil {
		return fmt.Errorf("gh api graphql resolveReviewThread: %w (%s)", err, strings.TrimSpace(stderr.String()))
	}
	return nil
}

// parsePRURL extracts owner, repo name, and PR number from a GitHub PR URL
// like https://github.com/owner/repo/pull/42.
func parsePRURL(prURL string) (owner, repo string, number int, err error) {
	u, err := url.Parse(prURL)
	if err != nil {
		return "", "", 0, fmt.Errorf("parse PR URL %q: %w", prURL, err)
	}
	parts := strings.Split(strings.Trim(u.Path, "/"), "/")
	if len(parts) < 4 || parts[2] != "pull" || parts[0] == "" || parts[1] == "" || parts[3] == "" {
		return "", "", 0, fmt.Errorf("unexpected PR URL shape: %q", prURL)
	}
	n, err := strconv.Atoi(parts[3])
	if err != nil {
		return "", "", 0, fmt.Errorf("PR number is not an integer in %q: %w", prURL, err)
	}
	return parts[0], parts[1], n, nil
}
